- name: Pull docker image of Calculator
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Stopping the running calculator
      shell: docker stop calculator && docker rm calculator

    - name: pull docker image
      shell: docker pull parulsachan86/scientific_calc

    - name: running container
      shell: docker run -it --name calculator -d parulsachan86/scientific_calc
